/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as UniverseRouteImport } from './routes/universe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as MeetingRecordsRouteImport } from './routes/meeting-records'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExecutionRouteImport } from './routes/execution'
import { Route as DriveRouteImport } from './routes/drive'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as BrainRouteImport } from './routes/brain'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActionsRouteImport } from './routes/actions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UseCasesIndexRouteImport } from './routes/use-cases.index'
import { Route as TopicsIndexRouteImport } from './routes/topics.index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as CompareIndexRouteImport } from './routes/compare.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UseCasesSlugRouteImport } from './routes/use-cases.$slug'
import { Route as TopicsSlugRouteImport } from './routes/topics.$slug'
import { Route as SharedTokenRouteImport } from './routes/shared.$token'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as DocsWorkerInstallRouteImport } from './routes/docs.worker-install'
import { Route as DocsLangRouteImport } from './routes/docs.$lang'
import { Route as DocsSplatRouteImport } from './routes/docs.$'
import { Route as CompareSlugRouteImport } from './routes/compare.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AgentProfileAgentIdRouteImport } from './routes/agent-profile.$agentId'
import { Route as AdminWorkspacesRouteImport } from './routes/admin/workspaces'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTasksRouteImport } from './routes/admin/tasks'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminNodesRouteImport } from './routes/admin/nodes'
import { Route as AdminFeedbackRouteImport } from './routes/admin/feedback'
import { Route as AdminExecutorsRouteImport } from './routes/admin/executors'
import { Route as AdminCommunityRouteImport } from './routes/admin/community'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as DocsLangIndexRouteImport } from './routes/docs.$lang.index'
import { Route as EmbedSessionTokenRouteImport } from './routes/embed.session.$token'
import { Route as DocsLangDocsSplatRouteImport } from './routes/docs.$lang.docs.$'

const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const UniverseRoute = UniverseRouteImport.update({
  id: '/universe',
  path: '/universe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingRecordsRoute = MeetingRecordsRouteImport.update({
  id: '/meeting-records',
  path: '/meeting-records',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionRoute = ExecutionRouteImport.update({
  id: '/execution',
  path: '/execution',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveRoute = DriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainRoute = BrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsRoute = ActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesIndexRoute = UseCasesIndexRouteImport.update({
  id: '/use-cases/',
  path: '/use-cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UseCasesSlugRoute = UseCasesSlugRouteImport.update({
  id: '/use-cases/$slug',
  path: '/use-cases/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsSlugRoute = TopicsSlugRouteImport.update({
  id: '/topics/$slug',
  path: '/topics/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedTokenRoute = SharedTokenRouteImport.update({
  id: '/shared/$token',
  path: '/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsWorkerInstallRoute = DocsWorkerInstallRouteImport.update({
  id: '/docs/worker-install',
  path: '/docs/worker-install',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsLangRoute = DocsLangRouteImport.update({
  id: '/docs/$lang',
  path: '/docs/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareSlugRoute = CompareSlugRouteImport.update({
  id: '/compare/$slug',
  path: '/compare/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentProfileAgentIdRoute = AgentProfileAgentIdRouteImport.update({
  id: '/agent-profile/$agentId',
  path: '/agent-profile/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkspacesRoute = AdminWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksRoute = AdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNodesRoute = AdminNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExecutorsRoute = AdminExecutorsRouteImport.update({
  id: '/executors',
  path: '/executors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunityRoute = AdminCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const DocsLangIndexRoute = DocsLangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsLangRoute,
} as any)
const EmbedSessionTokenRoute = EmbedSessionTokenRouteImport.update({
  id: '/embed/session/$token',
  path: '/embed/session/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsLangDocsSplatRoute = DocsLangDocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => DocsLangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRoute
  '/automations': typeof AutomationsRoute
  '/brain': typeof BrainRoute
  '/changelog': typeof ChangelogRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/download': typeof DownloadRoute
  '/drive': typeof DriveRoute
  '/execution': typeof ExecutionRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRoute
  '/kanban': typeof KanbanRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/meeting-records': typeof MeetingRecordsRoute
  '/models': typeof ModelsRoute
  '/onboarding': typeof OnboardingRoute
  '/overview': typeof OverviewRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/teams': typeof TeamsRoute
  '/terms': typeof TermsRoute
  '/universe': typeof UniverseRoute
  '/usage': typeof UsageRoute
  '/workspace': typeof WorkspaceRoute
  '/workspaces': typeof WorkspacesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/executors': typeof AdminExecutorsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/nodes': typeof AdminNodesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workspaces': typeof AdminWorkspacesRoute
  '/agent-profile/$agentId': typeof AgentProfileAgentIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/$lang': typeof DocsLangRouteWithChildren
  '/docs/worker-install': typeof DocsWorkerInstallRoute
  '/invite/$token': typeof InviteTokenRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/shared/$token': typeof SharedTokenRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/use-cases/': typeof UseCasesIndexRoute
  '/embed/session/$token': typeof EmbedSessionTokenRoute
  '/docs/$lang/': typeof DocsLangIndexRoute
  '/docs/$lang/docs/$': typeof DocsLangDocsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/agents': typeof AgentsRoute
  '/automations': typeof AutomationsRoute
  '/brain': typeof BrainRoute
  '/changelog': typeof ChangelogRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/download': typeof DownloadRoute
  '/drive': typeof DriveRoute
  '/execution': typeof ExecutionRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRoute
  '/kanban': typeof KanbanRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/meeting-records': typeof MeetingRecordsRoute
  '/models': typeof ModelsRoute
  '/onboarding': typeof OnboardingRoute
  '/overview': typeof OverviewRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/teams': typeof TeamsRoute
  '/terms': typeof TermsRoute
  '/universe': typeof UniverseRoute
  '/usage': typeof UsageRoute
  '/workspace': typeof WorkspaceRoute
  '/workspaces': typeof WorkspacesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/executors': typeof AdminExecutorsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/nodes': typeof AdminNodesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workspaces': typeof AdminWorkspacesRoute
  '/agent-profile/$agentId': typeof AgentProfileAgentIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/worker-install': typeof DocsWorkerInstallRoute
  '/invite/$token': typeof InviteTokenRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/shared/$token': typeof SharedTokenRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/compare': typeof CompareIndexRoute
  '/docs': typeof DocsIndexRoute
  '/topics': typeof TopicsIndexRoute
  '/use-cases': typeof UseCasesIndexRoute
  '/embed/session/$token': typeof EmbedSessionTokenRoute
  '/docs/$lang': typeof DocsLangIndexRoute
  '/docs/$lang/docs/$': typeof DocsLangDocsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRoute
  '/automations': typeof AutomationsRoute
  '/brain': typeof BrainRoute
  '/changelog': typeof ChangelogRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/download': typeof DownloadRoute
  '/drive': typeof DriveRoute
  '/execution': typeof ExecutionRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRoute
  '/kanban': typeof KanbanRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/meeting-records': typeof MeetingRecordsRoute
  '/models': typeof ModelsRoute
  '/onboarding': typeof OnboardingRoute
  '/overview': typeof OverviewRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/teams': typeof TeamsRoute
  '/terms': typeof TermsRoute
  '/universe': typeof UniverseRoute
  '/usage': typeof UsageRoute
  '/workspace': typeof WorkspaceRoute
  '/workspaces': typeof WorkspacesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/executors': typeof AdminExecutorsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/nodes': typeof AdminNodesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workspaces': typeof AdminWorkspacesRoute
  '/agent-profile/$agentId': typeof AgentProfileAgentIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/$lang': typeof DocsLangRouteWithChildren
  '/docs/worker-install': typeof DocsWorkerInstallRoute
  '/invite/$token': typeof InviteTokenRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/shared/$token': typeof SharedTokenRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/use-cases/': typeof UseCasesIndexRoute
  '/embed/session/$token': typeof EmbedSessionTokenRoute
  '/docs/$lang/': typeof DocsLangIndexRoute
  '/docs/$lang/docs/$': typeof DocsLangDocsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actions'
    | '/admin'
    | '/agents'
    | '/automations'
    | '/brain'
    | '/changelog'
    | '/chat'
    | '/dashboard'
    | '/download'
    | '/drive'
    | '/execution'
    | '/faq'
    | '/feedback'
    | '/inbox'
    | '/integrations'
    | '/kanban'
    | '/login'
    | '/mcp'
    | '/meeting-records'
    | '/models'
    | '/onboarding'
    | '/overview'
    | '/pricing'
    | '/privacy'
    | '/review'
    | '/settings'
    | '/skills'
    | '/teams'
    | '/terms'
    | '/universe'
    | '/usage'
    | '/workspace'
    | '/workspaces'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/community'
    | '/admin/executors'
    | '/admin/feedback'
    | '/admin/nodes'
    | '/admin/settings'
    | '/admin/tasks'
    | '/admin/users'
    | '/admin/workspaces'
    | '/agent-profile/$agentId'
    | '/blog/$slug'
    | '/compare/$slug'
    | '/docs/$'
    | '/docs/$lang'
    | '/docs/worker-install'
    | '/invite/$token'
    | '/profile/$userId'
    | '/shared/$token'
    | '/topics/$slug'
    | '/use-cases/$slug'
    | '/admin/'
    | '/blog/'
    | '/compare/'
    | '/docs/'
    | '/topics/'
    | '/use-cases/'
    | '/embed/session/$token'
    | '/docs/$lang/'
    | '/docs/$lang/docs/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actions'
    | '/agents'
    | '/automations'
    | '/brain'
    | '/changelog'
    | '/chat'
    | '/dashboard'
    | '/download'
    | '/drive'
    | '/execution'
    | '/faq'
    | '/feedback'
    | '/inbox'
    | '/integrations'
    | '/kanban'
    | '/login'
    | '/mcp'
    | '/meeting-records'
    | '/models'
    | '/onboarding'
    | '/overview'
    | '/pricing'
    | '/privacy'
    | '/review'
    | '/settings'
    | '/skills'
    | '/teams'
    | '/terms'
    | '/universe'
    | '/usage'
    | '/workspace'
    | '/workspaces'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/community'
    | '/admin/executors'
    | '/admin/feedback'
    | '/admin/nodes'
    | '/admin/settings'
    | '/admin/tasks'
    | '/admin/users'
    | '/admin/workspaces'
    | '/agent-profile/$agentId'
    | '/blog/$slug'
    | '/compare/$slug'
    | '/docs/$'
    | '/docs/worker-install'
    | '/invite/$token'
    | '/profile/$userId'
    | '/shared/$token'
    | '/topics/$slug'
    | '/use-cases/$slug'
    | '/admin'
    | '/blog'
    | '/compare'
    | '/docs'
    | '/topics'
    | '/use-cases'
    | '/embed/session/$token'
    | '/docs/$lang'
    | '/docs/$lang/docs/$'
  id:
    | '__root__'
    | '/'
    | '/actions'
    | '/admin'
    | '/agents'
    | '/automations'
    | '/brain'
    | '/changelog'
    | '/chat'
    | '/dashboard'
    | '/download'
    | '/drive'
    | '/execution'
    | '/faq'
    | '/feedback'
    | '/inbox'
    | '/integrations'
    | '/kanban'
    | '/login'
    | '/mcp'
    | '/meeting-records'
    | '/models'
    | '/onboarding'
    | '/overview'
    | '/pricing'
    | '/privacy'
    | '/review'
    | '/settings'
    | '/skills'
    | '/teams'
    | '/terms'
    | '/universe'
    | '/usage'
    | '/workspace'
    | '/workspaces'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/community'
    | '/admin/executors'
    | '/admin/feedback'
    | '/admin/nodes'
    | '/admin/settings'
    | '/admin/tasks'
    | '/admin/users'
    | '/admin/workspaces'
    | '/agent-profile/$agentId'
    | '/blog/$slug'
    | '/compare/$slug'
    | '/docs/$'
    | '/docs/$lang'
    | '/docs/worker-install'
    | '/invite/$token'
    | '/profile/$userId'
    | '/shared/$token'
    | '/topics/$slug'
    | '/use-cases/$slug'
    | '/admin/'
    | '/blog/'
    | '/compare/'
    | '/docs/'
    | '/topics/'
    | '/use-cases/'
    | '/embed/session/$token'
    | '/docs/$lang/'
    | '/docs/$lang/docs/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionsRoute: typeof ActionsRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgentsRoute: typeof AgentsRoute
  AutomationsRoute: typeof AutomationsRoute
  BrainRoute: typeof BrainRoute
  ChangelogRoute: typeof ChangelogRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  DownloadRoute: typeof DownloadRoute
  DriveRoute: typeof DriveRoute
  ExecutionRoute: typeof ExecutionRoute
  FaqRoute: typeof FaqRoute
  FeedbackRoute: typeof FeedbackRoute
  InboxRoute: typeof InboxRoute
  IntegrationsRoute: typeof IntegrationsRoute
  KanbanRoute: typeof KanbanRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  MeetingRecordsRoute: typeof MeetingRecordsRoute
  ModelsRoute: typeof ModelsRoute
  OnboardingRoute: typeof OnboardingRoute
  OverviewRoute: typeof OverviewRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
  TeamsRoute: typeof TeamsRoute
  TermsRoute: typeof TermsRoute
  UniverseRoute: typeof UniverseRoute
  UsageRoute: typeof UsageRoute
  WorkspaceRoute: typeof WorkspaceRoute
  WorkspacesRoute: typeof WorkspacesRoute
  AgentProfileAgentIdRoute: typeof AgentProfileAgentIdRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CompareSlugRoute: typeof CompareSlugRoute
  DocsSplatRoute: typeof DocsSplatRoute
  DocsLangRoute: typeof DocsLangRouteWithChildren
  DocsWorkerInstallRoute: typeof DocsWorkerInstallRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  SharedTokenRoute: typeof SharedTokenRoute
  TopicsSlugRoute: typeof TopicsSlugRoute
  UseCasesSlugRoute: typeof UseCasesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CompareIndexRoute: typeof CompareIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
  UseCasesIndexRoute: typeof UseCasesIndexRoute
  EmbedSessionTokenRoute: typeof EmbedSessionTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universe': {
      id: '/universe'
      path: '/universe'
      fullPath: '/universe'
      preLoaderRoute: typeof UniverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting-records': {
      id: '/meeting-records'
      path: '/meeting-records'
      fullPath: '/meeting-records'
      preLoaderRoute: typeof MeetingRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/execution': {
      id: '/execution'
      path: '/execution'
      fullPath: '/execution'
      preLoaderRoute: typeof ExecutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive': {
      id: '/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof DriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brain': {
      id: '/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof BrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/': {
      id: '/use-cases/'
      path: '/use-cases'
      fullPath: '/use-cases/'
      preLoaderRoute: typeof UseCasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/use-cases/$slug': {
      id: '/use-cases/$slug'
      path: '/use-cases/$slug'
      fullPath: '/use-cases/$slug'
      preLoaderRoute: typeof UseCasesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$slug': {
      id: '/topics/$slug'
      path: '/topics/$slug'
      fullPath: '/topics/$slug'
      preLoaderRoute: typeof TopicsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$token': {
      id: '/shared/$token'
      path: '/shared/$token'
      fullPath: '/shared/$token'
      preLoaderRoute: typeof SharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/worker-install': {
      id: '/docs/worker-install'
      path: '/docs/worker-install'
      fullPath: '/docs/worker-install'
      preLoaderRoute: typeof DocsWorkerInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$lang': {
      id: '/docs/$lang'
      path: '/docs/$lang'
      fullPath: '/docs/$lang'
      preLoaderRoute: typeof DocsLangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$slug': {
      id: '/compare/$slug'
      path: '/compare/$slug'
      fullPath: '/compare/$slug'
      preLoaderRoute: typeof CompareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-profile/$agentId': {
      id: '/agent-profile/$agentId'
      path: '/agent-profile/$agentId'
      fullPath: '/agent-profile/$agentId'
      preLoaderRoute: typeof AgentProfileAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workspaces': {
      id: '/admin/workspaces'
      path: '/workspaces'
      fullPath: '/admin/workspaces'
      preLoaderRoute: typeof AdminWorkspacesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tasks': {
      id: '/admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/nodes': {
      id: '/admin/nodes'
      path: '/nodes'
      fullPath: '/admin/nodes'
      preLoaderRoute: typeof AdminNodesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/executors': {
      id: '/admin/executors'
      path: '/executors'
      fullPath: '/admin/executors'
      preLoaderRoute: typeof AdminExecutorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/community': {
      id: '/admin/community'
      path: '/community'
      fullPath: '/admin/community'
      preLoaderRoute: typeof AdminCommunityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/docs/$lang/': {
      id: '/docs/$lang/'
      path: '/'
      fullPath: '/docs/$lang/'
      preLoaderRoute: typeof DocsLangIndexRouteImport
      parentRoute: typeof DocsLangRoute
    }
    '/embed/session/$token': {
      id: '/embed/session/$token'
      path: '/embed/session/$token'
      fullPath: '/embed/session/$token'
      preLoaderRoute: typeof EmbedSessionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$lang/docs/$': {
      id: '/docs/$lang/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$lang/docs/$'
      preLoaderRoute: typeof DocsLangDocsSplatRouteImport
      parentRoute: typeof DocsLangRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCommunityRoute: typeof AdminCommunityRoute
  AdminExecutorsRoute: typeof AdminExecutorsRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminNodesRoute: typeof AdminNodesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTasksRoute: typeof AdminTasksRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWorkspacesRoute: typeof AdminWorkspacesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCommunityRoute: AdminCommunityRoute,
  AdminExecutorsRoute: AdminExecutorsRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminNodesRoute: AdminNodesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTasksRoute: AdminTasksRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWorkspacesRoute: AdminWorkspacesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DocsLangRouteChildren {
  DocsLangIndexRoute: typeof DocsLangIndexRoute
  DocsLangDocsSplatRoute: typeof DocsLangDocsSplatRoute
}

const DocsLangRouteChildren: DocsLangRouteChildren = {
  DocsLangIndexRoute: DocsLangIndexRoute,
  DocsLangDocsSplatRoute: DocsLangDocsSplatRoute,
}

const DocsLangRouteWithChildren = DocsLangRoute._addFileChildren(
  DocsLangRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionsRoute: ActionsRoute,
  AdminRoute: AdminRouteWithChildren,
  AgentsRoute: AgentsRoute,
  AutomationsRoute: AutomationsRoute,
  BrainRoute: BrainRoute,
  ChangelogRoute: ChangelogRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  DownloadRoute: DownloadRoute,
  DriveRoute: DriveRoute,
  ExecutionRoute: ExecutionRoute,
  FaqRoute: FaqRoute,
  FeedbackRoute: FeedbackRoute,
  InboxRoute: InboxRoute,
  IntegrationsRoute: IntegrationsRoute,
  KanbanRoute: KanbanRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  MeetingRecordsRoute: MeetingRecordsRoute,
  ModelsRoute: ModelsRoute,
  OnboardingRoute: OnboardingRoute,
  OverviewRoute: OverviewRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
  TeamsRoute: TeamsRoute,
  TermsRoute: TermsRoute,
  UniverseRoute: UniverseRoute,
  UsageRoute: UsageRoute,
  WorkspaceRoute: WorkspaceRoute,
  WorkspacesRoute: WorkspacesRoute,
  AgentProfileAgentIdRoute: AgentProfileAgentIdRoute,
  BlogSlugRoute: BlogSlugRoute,
  CompareSlugRoute: CompareSlugRoute,
  DocsSplatRoute: DocsSplatRoute,
  DocsLangRoute: DocsLangRouteWithChildren,
  DocsWorkerInstallRoute: DocsWorkerInstallRoute,
  InviteTokenRoute: InviteTokenRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  SharedTokenRoute: SharedTokenRoute,
  TopicsSlugRoute: TopicsSlugRoute,
  UseCasesSlugRoute: UseCasesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  CompareIndexRoute: CompareIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  TopicsIndexRoute: TopicsIndexRoute,
  UseCasesIndexRoute: UseCasesIndexRoute,
  EmbedSessionTokenRoute: EmbedSessionTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
