import { CUSTOM_AGENT_CATEGORIES } from '@shared/custom-agent'

import { getBuiltInAgentAvatarUrl } from '../agent-avatar'
import type { CustomAgentTemplateOption } from './types'

const customAgentTemplateOptions: CustomAgentTemplateOption[] = [
  {
    id: 'executor',
    label: 'Executor',
    summary: '面向真实交付，适合直接实现、修改与落地。',
    description: '适合主力执行、代码实现、修复与交付任务。',
    category: 'engineering',
    avatarUrl: getBuiltInAgentAvatarUrl('engineering'),
    role: '交付执行 Agent',
    instructions: '你负责把任务直接落地。优先给可运行结果，必要时修改文件、运行命令、补充验证结论；不要只停留在分析层。',
    preferredRuntime: 'Pi',
    preferredModel: '',
    allowedMention: true,
    allowedDelegate: true,
    canWriteFiles: true,
    canRunCommands: true,
    delegatePreset: 'executor',
    defaultDelegateSessionRole: 'general',
    defaultDelegatePrompt: '先理解当前任务和代码上下文，再直接落地实现；完成后给出改动摘要、风险点和建议验证步骤。',
    delegateSessionMode: 'new-session',
    delegateBaseBranchMode: 'task',
    delegateBaseBranch: '',
    delegateWorkingDirectoryMode: 'worktree',
    tags: ['delivery', 'implementation', 'engineering'],
    recommendedSkillQueries: ['Code', 'debug', 'test'],
    recommendedMcpQueries: ['github', 'git', 'vibemux'],
  },
  {
    id: 'tester',
    label: 'Tester',
    summary: '面向验证与复测，适合测试、回归、定位和复现场景。',
    description: '适合 QA、测试、复现问题和回归检查。',
    category: 'engineering',
    avatarUrl: getBuiltInAgentAvatarUrl('testing'),
    role: '测试验证 Agent',
    instructions: '你优先做验证、复现和回归检查。先给复现路径、现象、影响范围，再给结论；除非必要，不要直接大改代码。',
    preferredRuntime: 'Pi',
    preferredModel: '',
    allowedMention: true,
    allowedDelegate: true,
    canWriteFiles: true,
    canRunCommands: true,
    delegatePreset: 'tester',
    defaultDelegateSessionRole: 'tester',
    defaultDelegatePrompt: '重点做复现、验证和回归；先说明测试路径、观察结果和风险判断，再给是否通过的结论。',
    delegateSessionMode: 'new-session',
    delegateBaseBranchMode: 'task',
    delegateBaseBranch: '',
    delegateWorkingDirectoryMode: 'worktree',
    tags: ['qa', 'testing', 'verification'],
    recommendedSkillQueries: ['test', 'debug'],
    recommendedMcpQueries: ['browser', 'vibemux'],
  },
  {
    id: 'reviewer',
    label: 'Reviewer',
    summary: '面向评审与风险控制，适合 code review、安全检查和验收。',
    description: '适合代码评审、风险审查、验收和质量把关。',
    category: 'engineering',
    avatarUrl: getBuiltInAgentAvatarUrl('review'),
    role: '评审验收 Agent',
    instructions: '你优先做评审与把关。明确指出风险、边界情况和是否可接受；默认先给审查结论，不直接替代执行人完成全部实现。',
    preferredRuntime: 'Pi',
    preferredModel: '',
    allowedMention: true,
    allowedDelegate: true,
    canWriteFiles: true,
    canRunCommands: true,
    delegatePreset: 'reviewer',
    defaultDelegateSessionRole: 'reviewer',
    defaultDelegatePrompt: '请从正确性、风险、边界条件和可维护性角度做评审，先给结论，再列问题和建议。',
    delegateSessionMode: 'reuse-current',
    delegateBaseBranchMode: 'task',
    delegateBaseBranch: '',
    delegateWorkingDirectoryMode: 'inherit',
    tags: ['review', 'acceptance', 'risk'],
    recommendedSkillQueries: ['security', 'test', 'review'],
    recommendedMcpQueries: ['github', 'git', 'vibemux'],
  },
  {
    id: 'doc-writer',
    label: 'Doc Writer',
    summary: '面向文档沉淀，适合补文档、说明、发布记录和操作手册。',
    description: '适合维护 PRD、README、变更说明和知识库内容。',
    category: 'product',
    avatarUrl: getBuiltInAgentAvatarUrl('docs'),
    role: '文档整理 Agent',
    instructions: '你负责把变更沉淀成清晰文档。优先输出结构化说明、约束、操作步骤和变更摘要，语言要简洁可复用。',
    preferredRuntime: 'Pi',
    preferredModel: '',
    allowedMention: true,
    allowedDelegate: true,
    canWriteFiles: true,
    canRunCommands: true,
    delegatePreset: 'doc-writer',
    defaultDelegateSessionRole: 'doc-writer',
    defaultDelegatePrompt: '请把当前任务的结果沉淀成可复用文档，先给结构化摘要，再补关键细节和后续注意事项。',
    delegateSessionMode: 'new-session',
    delegateBaseBranchMode: 'task',
    delegateBaseBranch: '',
    delegateWorkingDirectoryMode: 'worktree',
    tags: ['docs', 'knowledge', 'handoff'],
    recommendedSkillQueries: ['prd', 'writer', 'blog'],
    recommendedMcpQueries: ['notion', 'feishu', 'vibemux'],
  },
  {
    id: 'researcher',
    label: 'Researcher',
    summary: '面向调研与分析，适合背景调查、方案比较与问题拆解。',
    description: '适合前置调研、方案比较、竞品或技术背景分析。',
    category: 'research',
    avatarUrl: getBuiltInAgentAvatarUrl('research'),
    role: '研究分析 Agent',
    instructions: '你优先做信息搜集、背景分析和方案比较。先给结论摘要，再讲依据、选项和建议，不直接假设自己已经完成交付。',
    preferredRuntime: 'Pi',
    preferredModel: '',
    allowedMention: true,
    allowedDelegate: true,
    canWriteFiles: true,
    canRunCommands: true,
    delegatePreset: 'researcher',
    defaultDelegateSessionRole: 'researcher',
    defaultDelegatePrompt: '请先做背景调研和方案比较，给出明确建议、依据和未决问题，再说明下一步建议。',
    delegateSessionMode: 'reuse-current',
    delegateBaseBranchMode: 'task',
    delegateBaseBranch: '',
    delegateWorkingDirectoryMode: 'inherit',
    tags: ['research', 'analysis', 'strategy'],
    recommendedSkillQueries: ['research', 'market', 'last30', 'aminer'],
    recommendedMcpQueries: ['browser', 'search', 'vibemux'],
  },
]

export const CUSTOM_AGENT_TEMPLATE_OPTIONS = customAgentTemplateOptions
export const CUSTOM_AGENT_CATEGORY_VALUES = [...CUSTOM_AGENT_CATEGORIES]
