import {
  registerAgent,
  updateAgent,
  agentHeartbeat,
  getAgent,
  getAllAgents,
  getUserAgents,
  deleteAgent,
  createAgentTask,
  getAgentTasks,
  startAgentTask,
  completeAgentTask,
  failAgentTask,
  createAgentCron,
  getAgentCrons,
  updateAgentCron,
  toggleAgentCron,
  deleteAgentCron,
  getAgentHeartbeats,
} from '../../repositories/agent'
import { loadState } from '../../storage/app-state-store'

export const agentService = {
  registerAgent,
  updateAgent,
  agentHeartbeat,
  getAgent,
  getAllAgents,
  getUserAgents,
  deleteAgent,
  createAgentTask,
  getAgentTasks,
  createAgentCron,
  getAgentCrons,
  updateAgentCron,
  toggleAgentCron,
  deleteAgentCron,
  getAgentHeartbeats,
}
