// [INPUT]: 复制输入
// [OUTPUT]: 脱敏复制
// [POS]: Worker Console 复制工具
// [PROTOCOL]: 变更时更新此头部，然后检查 AGENTS.md

export const LOCALE_KEY = 'vibemux-worker-console-locale'

const englishCopy = {
    eyebrow: 'Local Runtime Console',
    consoleTitle: 'Operate your worker from a status-first control console.',
    consoleBody: 'See the current health first, then jump straight into pairing, configuration, bindings, or diagnostics.',
    consoleTitleFocus: 'Connect this worker to the cloud first.',
    consoleBodyFocus: 'If the page says offline, focus on pairing and cloud connection first. Everything else can wait.',
    language: 'Language',
    tabOverview: 'Overview',
    tabSettings: 'Connection Settings',
    tabBindings: 'Project Bindings',
    tabDoctor: 'Diagnostics',
    tabSessions: 'Local Sessions',
    refresh: 'Refresh',
    refreshSessions: 'Refresh Sessions',
    expand: 'Expand',
    collapse: 'Collapse',
    doctor: 'Run Doctor',
    bootstrap: 'Prepare Runtime',
    connect: 'Connect Cloud',
    disconnect: 'Disconnect',
    pair: 'Pair Worker',
    reset: 'Clear Local Config',
    saveConfig: 'Save Configuration',
    addBinding: 'Add Binding',
    saveBindings: 'Save Bindings',
    reviewDoctor: 'Review Diagnostics',
    nextStep: 'Next Step',
    cloudStatusLabel: 'Cloud Status',
    machineNameLabel: 'Machine Name',
    cloudUrlLabel: 'Cloud URL',
    effectiveCloudUrlLabel: 'Selected Cloud URL',
    routeAssignmentLabel: 'Route Assignment',
    routeProbesLabel: 'Route Probes',
    meshStatusLabel: 'Mesh',
    meshIpLabel: 'Mesh IP',
    meshRouteLabel: 'Mesh Route',
    meshPeersLabel: 'Mesh Peers',
    meshReportedAtLabel: 'Mesh Reported',
    meshDisabled: 'Disabled',
    meshInstalling: 'Installing',
    meshConnecting: 'Connecting',
    meshReady: 'Ready',
    meshDegraded: 'Degraded',
    meshError: 'Error',
    lastHeartbeatLabel: 'Last Heartbeat',
    statusPairing: 'Pairing',
    statusCloud: 'Cloud Session',
    statusDaemon: 'Daemon',
    statusDoctor: 'Doctor',
    runtimeTitle: 'Overview',
    runtimeBody: 'Check the current runtime state, recent activity, and the quickest recovery actions.',
    mcpTitle: 'MCP Status',
    mcpBody: 'Show the worker-visible MCP servers, whether they are materialized, and how acting-user scope is applied.',
    mcpConfigured: 'Configured MCP',
    mcpEnabled: 'Enabled MCP',
    mcpEffective: 'Effective MCP',
    mcpActingUserMode: 'Acting User',
    mcpBuiltIn: 'Built-in wemux',
    mcpServersTitle: 'Effective MCP Servers',
    mcpIssuesTitle: 'MCP Readiness',
    mcpNoIssues: 'No MCP-specific blockers detected.',
    mcpEmpty: 'No MCP servers are configured on this worker.',
    mcpScopeDynamic: 'Dynamic per request',
    mcpScopeNeedsPairing: 'Pairing required',
    mcpScopeDisabled: 'Disabled',
    mcpBuiltinReady: 'Enabled and ready',
    mcpBuiltinPending: 'Enabled, waiting for pairing',
    mcpBuiltinDisabled: 'Not enabled',
    mcpIssueBuiltinPairing: 'Built-in wemux MCP is enabled but the worker is not paired, so executor auth headers cannot be injected yet.',
    mcpIssueNoEnabledServers: 'No MCP server is enabled. The worker will run without MCP tools.',
    mcpKindBuiltin: 'Built-in wemux',
    mcpKindRemote: 'Remote HTTP/SSE',
    mcpKindStdio: 'Local stdio',
    mcpKindCustom: 'Custom target',
    mcpStatusEnabled: 'Enabled',
    mcpStatusDisabled: 'Disabled',
    mcpEffectiveLabel: 'Materialized',
    mcpConfiguredLabel: 'Configured only',
    mcpTargetLabel: 'Target',
    mcpEndpointLabel: 'Endpoint',
    mcpCommandLabel: 'Command',
    mcpHeadersLabel: 'Headers',
    mcpTransportLabel: 'Transport / Capability',
    mcpActingUserLabel: 'Acting User Scope',
    mcpScopeEnabledLabel: 'Supported',
    mcpScopeDisabledLabel: 'Not used',
    quickActionsTitle: 'Quick Actions',
    quickActionsBody: 'Use the most frequent actions without leaving the overview.',
    recentIssuesTitle: 'Recent Issues',
    recentIssuesBody: 'Only surface information that needs attention or helps with the latest incident.',
    noIssues: 'No recent runtime warnings. The worker looks healthy.',
    settingsTitle: 'Connection Settings',
    settingsBody: 'Pair the machine, tune runtime settings, and keep risky actions isolated.',
    quickConnectBody: 'Only fill in the pairing code, display name, and cloud URL here. Connecting will save the latest cloud URL automatically.',
    rePairingHint: 'If this worker is already paired, paste a new pairing code and click Pair again to move it under that control-plane account.',
    pairingSectionTitle: 'Pair Worker',
    pairingSectionBody: 'Use the pairing code from the control plane to attach this machine.',
    configSectionTitle: 'Base Configuration',
    configSectionBody: 'Configure the cloud target, workspace root, and concurrency.',
    capabilitiesSectionTitle: 'Execution Capabilities',
    capabilitiesSectionBody: 'Labels and capabilities help the control plane route work correctly.',
    machineSectionTitle: 'Machine Summary',
    machineSectionBody: 'Expose the minimum identifiers needed for troubleshooting.',
    connectionActionsTitle: 'Connection Actions',
    connectionActionsBody: 'Connect when paired, disconnect only when you need to stop the current session.',
    advancedSettingsTitle: 'Advanced Settings',
    advancedSettingsBody: 'Only open this when you need workspace, capability, or local troubleshooting details.',
    showAdvancedSettings: 'Show Advanced',
    hideAdvancedSettings: 'Hide Advanced',
    dangerZoneTitle: 'Danger Zone',
    dangerZoneBody: 'Keep destructive actions separate from normal editing to avoid mistakes.',
    bindingsTitle: 'Project Bindings',
    bindingsBody: 'Reuse local repositories when task metadata matches known project information.',
    sessionsTitle: 'Local Agent Sessions',
    sessionsBody: 'Discover local Claude Code, OpenCode, Codex, and Pi sessions on this machine, then open a normalized read-only transcript.',
    sessionsLoading: 'Scanning local session stores…',
    sessionsEmpty: 'No local sessions found in Claude Code, OpenCode, Codex, or Pi.',
    sessionsNoSelection: 'Choose a session on the left to read it here.',
    sessionsNoEntries: 'This session was found, but no readable text entries were extracted.',
    sessionsCount: 'Entries',
    sessionStartedAt: 'Started At',
    sessionUpdatedAt: 'Updated At',
    sessionCwd: 'Working Directory',
    sessionSourceClaude: 'Claude Code',
    sessionSourceOpencode: 'OpenCode',
    sessionSourceCodex: 'Codex',
    sessionSourcePi: 'Pi',
    doctorTitle: 'Diagnostics',
    doctorBody: 'Show a clear summary first, then list failed checks before anything else.',
    failedItemsTitle: 'Needs Attention',
    passedItemsTitle: 'Healthy Checks',
    noFailedItems: 'No failed checks right now.',
    developerDataTitle: 'Developer Data',
    doctorPending: 'Control plane probe has not run yet',
    officialPending: 'Official site probe has not run yet',
    doctorPassed: 'Doctor checks passed',
    doctorFailed: 'Doctor found issues',
    doctorSummary: 'Passed {passed} / {total}, failed {failed}',
    viewRaw: 'View sanitized raw JSON',
    cloudProbe: 'Control Plane',
    officialSite: 'OpenCode',
    pairingCode: 'Pairing Code',
    pairingCodePlaceholder: 'Paste the pairing code from the control plane',
    workerName: 'Display Name',
    workerNamePlaceholder: 'For example: MacBook Air Worker',
    projectIdLabel: 'Project ID',
    repoUrlLabel: 'Repo URL',
    localPathLabel: 'Local Path',
    labels: 'Labels',
    labelsPlaceholder: 'One label per line',
    capabilities: 'Capabilities',
    capabilitiesPlaceholder: 'One capability per line',
    workspaceRootLabel: 'Workspace Root',
    maxConcurrencyLabel: 'Max Concurrency',
    localServerPortLabel: 'Local Console Port',
    executorIdLabel: 'Executor ID',
    machineIdLabel: 'Machine ID',
    runningQueued: 'Running / Queued',
    lastConnectAttempt: 'Last Connect Attempt',
    lastRouteSelection: 'Last Route Selection',
    lastDisconnect: 'Last Disconnect',
    lastTaskActivity: 'Last Task Activity',
    lastError: 'Last Error',
    daemonMode: 'Daemon Mode',
    workspaceFirst: 'Prefer Local Paths',
    unpaired: 'Unpaired',
    online: 'Cloud Online',
    offline: 'Cloud Offline',
    paired: 'Paired',
    waitingPairing: 'Waiting for pairing',
    ready: 'READY',
    check: 'CHECK',
    remove: 'Remove',
    noBindings: 'No project bindings yet. Add one for repositories you use often.',
    refreshed: 'Status refreshed.',
    doctorDone: 'Doctor finished.',
    runtimeReady: 'Runtime preparation finished.',
    configSaved: 'Configuration saved.',
    saving: 'Saving…',
    pairDone: 'Pairing complete.',
    pairingInProgress: 'Pairing…',
    pairingCodeRequired: 'Pairing code is required before pairing.',
    pairingSuccessTitle: 'Pairing successful',
    pairingSuccessBody: 'This worker is paired. Next, connect it to the cloud.',
    resetDone: 'Local configuration cleared.',
    bindingsSaved: 'Project bindings saved.',
    connectDone: 'Cloud connection established.',
    connecting: 'Connecting…',
    disconnectDone: 'Cloud connection closed.',
    disconnecting: 'Disconnecting…',
    cloudConnectingTitle: 'Connecting to cloud',
    cloudConnectingBody: 'Please wait a moment. The page will refresh after the connection result comes back.',
    cloudConnectedTitle: 'Connected to cloud',
    cloudConnectedBody: 'This worker is online and ready to receive cloud work.',
    cloudDisconnectedTitle: 'Not connected to cloud',
    cloudDisconnectedBody: 'Pair this worker first, then connect it to the cloud so it can receive tasks.',
    cloudDisconnectedPairedBody: 'Pairing is done. Click Connect Cloud to bring this worker online.',
    cloudDisconnectingBody: 'The current cloud session is being closed. Please wait a moment.',
    connectionFailedTitle: 'Connection action failed',
    cloudUrlRequired: 'Cloud URL is required before connecting.',
    none: 'None',
    na: 'n/a',
} as const

export const dictionary = {
  en: englishCopy,
  zh: englishCopy,
} as const
