// Electron desktop release manifest generator.
//
// [INPUT]: electron-builder artifacts downloaded into --bundles-dir
// [OUTPUT]: downloads.json + notes.txt for the public desktop download page
// [POS]: Electron release metadata adapter; updater metadata is generated by electron-builder
// [PROTOCOL]: change this header when editing, then check AGENTS.md

import { createHash } from 'node:crypto'
import { mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const args = process.argv.slice(2)

const readFlag = (name) => {
  const index = args.indexOf(name)
  return index >= 0 ? args[index + 1] : undefined
}

const usage = `desktop-release.mjs manifest [flags]

  --version <v>          Product version
  --bundles-dir <path>   Directory containing Electron artifacts
  --manifest <path>      Download manifest template
  --out-dir <path>       Output directory (downloads.json + notes.txt)
  --repo <owner/repo>    GitHub repository (default: GITHUB_REPOSITORY or wemux-ai/wemux)
`

if (args.includes('--help') || args.includes('-h') || args[0] !== 'manifest') {
  process.stdout.write(usage)
  process.exit(args.includes('--help') || args.includes('-h') ? 0 : 1)
}

const version = readFlag('--version')
const bundlesDir = path.resolve(readFlag('--bundles-dir') || 'bundles')
const manifestPath = path.resolve(
  readFlag('--manifest') || path.join(repoRoot, 'apps/web/src/data/desktop-downloads.json'),
)
const outDir = path.resolve(readFlag('--out-dir') || 'release-out')
const repo = readFlag('--repo') || process.env.GITHUB_REPOSITORY?.trim() || 'wemux-ai/wemux'

if (!version) throw new Error('manifest requires --version')

const collectFiles = (directory) => readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
  const filePath = path.join(directory, entry.name)
  return entry.isDirectory() ? collectFiles(filePath) : [filePath]
})

const files = collectFiles(bundlesDir)
const expectedArtifacts = {
  'darwin-aarch64': `Wemux-${version}-arm64.dmg`,
  'darwin-x86_64': `Wemux-${version}-x64.dmg`,
  'windows-x86_64': `Wemux-${version}-x64-setup.exe`,
  'linux-x86_64': `Wemux-${version}-x64.AppImage`,
}

const sha256File = (filePath) => {
  const hash = createHash('sha256')
  hash.update(readFileSync(filePath))
  return hash.digest('hex')
}

const template = JSON.parse(readFileSync(manifestPath, 'utf8'))
const manifest = structuredClone(template)
manifest.version = version
manifest.publishedAt = new Date().toISOString()
manifest.notes = `Wemux Electron desktop v${version}`

for (const platform of manifest.platforms) {
  const expectedName = expectedArtifacts[platform.id]
  if (!expectedName) continue
  const artifactPath = files.find((filePath) => path.basename(filePath) === expectedName)
  if (!artifactPath) throw new Error(`missing Electron artifact for ${platform.id}: ${expectedName}`)
  platform.file = expectedName
  platform.url = `https://github.com/${repo}/releases/download/v${version}/${expectedName}`
  platform.sizeBytes = statSync(artifactPath).size
  platform.sha256 = sha256File(artifactPath)
}

mkdirSync(outDir, { recursive: true })
writeFileSync(path.join(outDir, 'downloads.json'), `${JSON.stringify(manifest, null, 2)}\n`)
writeFileSync(path.join(outDir, 'notes.txt'), `${manifest.notes}\n`)
console.log(`[desktop-release] generated ${path.join(outDir, 'downloads.json')}`)
