export {
  DEFAULT_WORKSPACE_ROOT,
  buildWorkspaceRepoPath,
  buildWorkspaceProjectRootPath,
  buildWorkspaceWorktreePath,
  extractRepositoryName,
  getWorkspaceProjectBaseDir,
  getWorkspaceNodeDir,
  getConfiguredWorkspaceRoot,
  isManagedWorkspaceOwnedProjectPath,
  isManagedWorkspaceProjectPath,
  isManagedWorkspaceRepoPath,
  getWorkspaceProjectKey,
  getWorkspaceRepoBaseDir,
  getWorkspaceRepoName,
  getWorkspaceUserScopeDir,
  getWorkspaceWorktreeBaseDir,
  normalizeWorkspaceRoot,
  resolveTaskWorktreePath,
} from '@shared/workspace-paths'
